url: https://cunningham.github.io
baseurl: /

# Site settings
title: Aligned Light Healing
email: andrea@alignedlighthealing.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Andrea Cunningham
  pic: 1
  position: Owner/Practitioner
  social:
    - title: instagram
    url: http://instagram.com/alignedlighthealing


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/alignedlighthealing

# Postal address (add as many lines as necessary)
address:
  - line: 235 NE 6th Ave 
  - line: Camas, WA 98607

# Build settings
markdown: kramdown
permalink: pretty